import { useCallback, useEffect, useMemo, useState } from 'react';
import { cases, evidenceMeta } from './data/cases';
import { playTone } from './audio';
import { formatTimer, isCorrect, isMissionComplete, unlockEvidence } from './game';
import type { EvidenceKey, Phase } from './types';
import { CaseCard } from './components/CaseCard';
import { ChatCase } from './components/ChatCase';
import { MythCase } from './components/MythCase';
import { SupportNetwork } from './components/SupportNetwork';
import { EvidenceBoard } from './components/EvidenceBoard';
import { FinalScreen } from './components/FinalScreen';
import { Modal } from './components/Modal';

const STORAGE = 'quiz-detective-progress-v1';
type Saved = { phase: Phase; caseIndex: number; unlocked: EvidenceKey[]; sound: boolean };
function readSaved(): Saved | null { try { const raw = localStorage.getItem(STORAGE); return raw ? JSON.parse(raw) as Saved : null; } catch { return null; } }

export default function App() {
  const [saved] = useState(readSaved);
  const [phase, setPhase] = useState<Phase>(saved?.phase ?? 'intro');
  const [caseIndex, setCaseIndex] = useState(saved?.caseIndex ?? 0);
  const [unlocked, setUnlocked] = useState<EvidenceKey[]>(saved?.unlocked ?? []);
  const [sound, setSound] = useState(saved?.sound ?? true);
  const [selected, setSelected] = useState<number | null>(null);
  const [lastCorrect, setLastCorrect] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const [officeClue, setOfficeClue] = useState<string | null>(null);
  const [timerSeconds, setTimerSeconds] = useState<number | null>(null);
  const [timerExpired, setTimerExpired] = useState(false);
  const [soundPulse, setSoundPulse] = useState(false);
  const activeCase = cases[caseIndex];
  const progress = Math.round((caseIndex / cases.length) * 100);
  const persist = useCallback((next?: Partial<Saved>) => { try { localStorage.setItem(STORAGE, JSON.stringify({ phase, caseIndex, unlocked, sound, ...next })); } catch { /* optional */ } }, [phase, caseIndex, unlocked, sound]);
  useEffect(() => { persist(); }, [persist]);
  useEffect(() => { if (phase !== 'case' || timerSeconds === null || timerSeconds <= 0) return; const timer = window.setTimeout(() => { if (timerSeconds === 1) setTimerExpired(true); setTimerSeconds(value => value === null ? null : Math.max(0, value - 1)); }, 1000); return () => window.clearTimeout(timer); }, [phase, timerSeconds]);
  const startMission = () => { playTone('click', sound); setOfficeClue(null); setPhase('office'); };
  const investigate = (clue: string, tone: 'paper' | 'phone' | 'scanner' = 'paper') => { playTone(tone, sound); setOfficeClue(clue); };
  const openCase = () => { const tone = activeCase.kind === 'chat' ? 'phone' : activeCase.kind === 'scanner' ? 'scanner' : activeCase.kind === 'myth' ? 'seal' : 'paper'; playTone(tone, sound); setSelected(null); setTimerExpired(false); setTimerSeconds(activeCase.challengeSeconds ?? null); setPhase('case'); };
  const finishAnswer = (correct: boolean) => { setLastCorrect(correct); setPhase('feedback'); playTone(correct ? 'clue' : 'click', sound); };
  const handleChoice = (choice: number) => { if (phase !== 'case') return; setSelected(choice); if (activeCase.kind !== 'network') finishAnswer(isCorrect(choice, activeCase.correctIndex ?? -1)); };
  const completeNetwork = () => { setSelected(0); finishAnswer(true); };
  const continueAfterFeedback = () => { if (!lastCorrect) { setPhase('case'); setSelected(null); setTimerSeconds(activeCase.challengeSeconds ?? null); setTimerExpired(false); return; } const nextUnlocked = unlockEvidence(unlocked, activeCase.evidence); setUnlocked(nextUnlocked); playTone('clue', sound); setPhase('unlock'); };
  const continueAfterUnlock = () => { if (isMissionComplete(caseIndex, cases.length)) { setPhase('final_unlock'); playTone('safe', sound); } else { setCaseIndex(caseIndex + 1); setSelected(null); setOfficeClue(null); setPhase('office'); } };
  const reset = () => { localStorage.removeItem(STORAGE); setPhase('intro'); setCaseIndex(0); setUnlocked([]); setSelected(null); setOfficeClue(null); setResetOpen(false); };
  const fullscreen = async () => { try { if (!document.fullscreenElement) await document.documentElement.requestFullscreen(); else await document.exitFullscreen(); } catch { document.body.classList.toggle('focus-mode'); } };
  const testSound = () => { playTone('clue', sound); setSoundPulse(true); window.setTimeout(() => setSoundPulse(false), 1800); };
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'f' || event.key === 'F') void fullscreen(); if (event.key === 'Enter') { if (phase === 'intro') startMission(); else if (phase === 'office') openCase(); else if (phase === 'feedback') continueAfterFeedback(); else if (phase === 'unlock') continueAfterUnlock(); } if (phase === 'case' && ['1', '2', '3'].includes(event.key)) handleChoice(Number(event.key) - 1); if (event.key === 'Escape') setResetOpen(false); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); });

  const header = <header className="topbar"><div className="brand"><span className="brand-mark">QD</span><span><b>QUIZ DETECTIVE</b><small>OPERACIÓN: CÓDIGO DE APOYO</small></span></div><div className="top-actions"><button className="utility-button" onClick={() => setSound(x => !x)} aria-label="Activar o desactivar sonido">{sound ? '🔊' : '🔇'} SONIDO {sound ? 'ON' : 'OFF'}</button><button className="utility-button" onClick={testSound}>♪ PROBAR SONIDO</button><button className="utility-button" onClick={() => void fullscreen()}>⛶ PANTALLA COMPLETA <kbd>F</kbd></button><button className="reset-button" onClick={() => setResetOpen(true)}>↺ REINICIAR MISIÓN</button></div></header>;
  const intro = <main className="intro-wrap"><div className="intro-kicker"><span className="intro-mark">QD</span><span>ARCHIVO 05 · CLASIFICACIÓN: EQUIPO</span></div><div className="intro-content"><p className="eyebrow">UNA MISIÓN COOPERATIVA</p><h1>QUIZ DETECTIVE<br /><span>Operación: Código de Apoyo</span></h1><p className="intro-lead">Ha aparecido un expediente incompleto.<br />El Código de Apoyo fue dividido en cinco evidencias.</p><p className="intro-detail">El escuadrón deberá investigar los casos, identificar pistas correctas y recuperar las piezas antes de cerrar el expediente.</p><button className="primary-button" onClick={startMission} data-testid="start-mission">Iniciar investigación <span>→</span></button><div className="intro-hint">ENTER para comenzar <i>·</i> F pantalla completa</div></div><div className="intro-file"><div className="file-top"><span>EXPEDIENTE</span><strong>05-A</strong></div><div className="file-seal">CONFIDENCIAL</div><div className="file-lines"><i /><i /><i /><i /></div><div className="file-clue">⌁ &nbsp; El bienestar del equipo es la primera evidencia.</div></div></main>;
  const office = <main className="office-wrap"><div className="office-copy"><p className="eyebrow">OFICINA CENTRAL · SECTOR 05</p><h1>Escuadrón,<br /><span>hay una pista</span><br />esperando.</h1><p className="lead">Cada caso guarda una pieza del <strong>Código de Apoyo</strong>. Investiguen el tablero, conversen y elijan juntos qué evidencia merece su atención.</p><div className="mission-progress"><div className="progress-label"><span>PROGRESO DE MISIÓN</span><strong>{caseIndex}/10 casos</strong></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div></div><button className="primary-button" onClick={openCase} data-testid="enter-case">{caseIndex === 0 ? 'Abrir primer expediente' : `Continuar en caso ${caseIndex + 1}`} <span>→</span></button>{officeClue && <div className="office-clue" role="status" data-testid="office-clue"><span>✦ PISTA DE LA OFICINA</span><strong>{officeClue}</strong></div>}</div><div className="detective-room" aria-label="Oficina interactiva"><div className="window-light" /><button aria-label="Investigar lámpara" className="room-lamp room-object" onClick={() => investigate('La luz suave señala que el equipo puede investigar con calma.')}>◒</button><button aria-label="Investigar tablero" className="room-board room-object" onClick={() => investigate('El tablero guarda cinco lugares. Cada pieza llega después de conversar en equipo.')}><span className="board-pin" /><span className="board-label">EVIDENCIAS</span><div className="mini-slots">{unlocked.map(key => <span key={key}>{evidenceMeta[key].icon}</span>)}{Array.from({ length: 5 - unlocked.length }).map((_, i) => <span key={`empty-${i}`}>?</span>)}</div></button><div className="room-desk"><button aria-label="Abrir expediente" className="paper-stack room-object" onClick={() => investigate('Nota secreta: no hay que resolverlo todo a solas.')}>✎<small>EXPEDIENTE<br />ABIERTO</small></button><button aria-label="Escuchar teléfono" className="phone room-object" onClick={() => investigate('Línea segura: hablar con alguien de confianza es una pista valiosa.', 'phone')}>⌁<small>LÍNEA<br />SEGURA</small></button><button aria-label="Usar lupa" className="magnifier room-object" onClick={() => investigate('Escáner listo: observa, escucha y decide en equipo.', 'scanner')}>⌕</button><div className="desk-label">OFICINA DE INVESTIGACIÓN</div></div></div></main>;
  const caseView = useMemo(() => { if (activeCase.kind === 'chat') return <ChatCase item={activeCase} selected={selected} onSelect={handleChoice} />; if (activeCase.kind === 'myth') return <MythCase item={activeCase} selected={selected} onSelect={handleChoice} />; if (activeCase.kind === 'network') return <SupportNetwork item={activeCase} onComplete={completeNetwork} />; return <CaseCard item={activeCase} selected={selected} onSelect={handleChoice} />; }, [activeCase, selected, phase]);
  const caseScreen = <main className="case-wrap"><div className="case-nav"><button className="back-button" onClick={() => setPhase('office')}>← Oficina</button><span>CASO {String(activeCase.id).padStart(2, '0')} / 10</span><span className="case-dots">{cases.map(item => <i key={item.id} className={item.id <= activeCase.id ? 'on' : ''} />)}</span></div><div className="decision-strip"><strong>DECISIÓN DEL ESCUADRÓN</strong><span>Conversen 20–30 segundos y voten con los dedos: 1 = A · 2 = B · 3 = C</span>{timerSeconds !== null && <span className={`timer-pill ${timerSeconds < 8 ? 'urgent' : ''}`} data-testid="timer"><b>◷ {activeCase.challengeLabel}</b><strong>{formatTimer(timerSeconds)}</strong></span>}{timerExpired && <span className="timer-help" data-testid="timer-expired">El tiempo de investigación terminó. No pasa nada: hay una pista extra para continuar.</span>}</div><div className="case-layout"><div className="case-intro"><p className="eyebrow">INVESTIGACIÓN EN CURSO</p><h1>Una pista<br /><span>puede cambiarlo todo.</span></h1><p>Lean la evidencia en equipo. No hay respuestas perfectas: hay decisiones que ayudan a cuidar.</p><div className="case-note">⌁ <span>PISTA DEL CASO</span><small>{activeCase.clue}</small></div></div>{caseView}</div></main>;
  let content: React.ReactNode = phase === 'intro' ? intro : office;
  if (phase === 'case') content = caseScreen;
  if (phase === 'feedback') content = <main className="feedback-wrap"><div className={`feedback-card ${lastCorrect ? 'correct' : 'retry'}`} data-testid="feedback"><div className="feedback-icon">{lastCorrect ? '✓' : '↻'}</div><p className="eyebrow">{lastCorrect ? 'EVIDENCIA CONFIRMADA' : 'PISTA FALSA'}</p><h1>{lastCorrect ? 'El equipo leyó bien la escena.' : 'Revisemos nuevamente las evidencias.'}</h1><p>{lastCorrect ? activeCase.feedback : 'No pasa nada. El objetivo es aprender y volver a investigar con calma.'}</p><button className="primary-button" onClick={continueAfterFeedback} data-testid="feedback-continue">{lastCorrect ? 'Revelar evidencia' : 'Intentar de nuevo'} <span>→</span></button></div></main>;
  if (phase === 'unlock') content = <main className="unlock-wrap"><div className="unlock-card" data-testid="evidence-unlock"><div className="unlock-icon">{evidenceMeta[activeCase.evidence].icon}</div><p className="eyebrow">NUEVA PIEZA RECUPERADA</p><h1>{evidenceMeta[activeCase.evidence].label.toUpperCase()}</h1><p>{evidenceMeta[activeCase.evidence].short}</p><div className="unlock-line" /><button className="primary-button" onClick={continueAfterUnlock}>Volver al tablero <span>→</span></button></div></main>;
  if (phase === 'final_unlock') content = <main className="safe-wrap"><div className="safe"><div className="safe-door"><span>✦</span><b>CAJA<br />SEGURA</b></div><div className="safe-copy"><p className="eyebrow">LAS CINCO PIEZAS ESTÁN REUNIDAS</p><h1>El expediente<br /><span>puede cerrarse.</span></h1><p>El Código de Apoyo está listo. La oficina ha encontrado una respuesta para llevar al equipo.</p><button className="primary-button" onClick={() => { playTone('safe', sound); setPhase('reflection'); }} data-testid="open-safe">Abrir caja fuerte <span>→</span></button></div></div></main>;
  if (phase === 'reflection') content = <main className="final-wrap"><FinalScreen onRestart={() => setResetOpen(true)} /></main>;
  return <div className="app-shell">{header}<div className="ambient-orb orb-one" /><div className="ambient-orb orb-two" />{content}<EvidenceBoard unlocked={unlocked} compact={phase !== 'intro' && phase !== 'office'} />{soundPulse && <div className="sound-toast" role="status" data-testid="sound-toast">{sound ? '♪ Prueba de sonido: pista encontrada' : '🔇 El sonido está apagado'}</div>}{resetOpen && <Modal title="¿Reiniciar la misión?" onCancel={() => setResetOpen(false)} onConfirm={reset}>Se borrará el progreso de esta misión en este navegador. No se guarda ninguna respuesta personal.</Modal>}</div>;
}
